name: 'Check renovate-config.json'

on:
  push:
    branches:
      - 'master'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  test:
    uses: SlashNephy/.github/.github/workflows/yarn-run.yml@master
    with:
      script: 'test'

  lint:
    uses: SlashNephy/.github/.github/workflows/yarn-lint.yml@master
    with:
      enable-eslint: false
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name != 'pull_request'
    uses: SlashNephy/.github/.github/workflows/yarn-format.yml@master
    permissions:
      contents: 'write'
